import { db } from '../src/lib/db';

const categories = [
  {
    id: 'cat-1',
    name: 'Электроинструменты',
    slug: 'power-tools',
    icon: 'Zap',
    image: '/categories/power-tools.png',
  },
  {
    id: 'cat-2',
    name: 'Ручной инструмент',
    slug: 'hand-tools',
    icon: 'Wrench',
    image: '/categories/hand-tools.png',
  },
  {
    id: 'cat-3',
    name: 'Расходные материалы',
    slug: 'consumables',
    icon: 'CircleDot',
    image: '/categories/consumables.png',
  },
  {
    id: 'cat-4',
    name: 'Садовая техника',
    slug: 'garden',
    icon: 'TreePine',
    image: '/categories/garden.png',
  },
  {
    id: 'cat-5',
    name: 'Строительное оборудование',
    slug: 'construction-equip',
    icon: 'Building2',
    image: '/categories/construction-equip.png',
  },
];

const products = [
  // Электроинструменты
  {
    id: 'prod-1',
    name: 'Перфоратор Bosch GBH 2-28',
    slug: 'perforator-bosch-gbh-2-28',
    description: 'Мощный перфоратор SDS-plus для профессионального использования. 3 режима работы: сверление, долбление, сверление с долблением. Электронная регулировка частоты вращения.',
    price: 18990,
    oldPrice: 22490,
    categoryId: 'cat-1',
    image: '/products/perforator.png',
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    brand: 'Bosch',
    isNew: false,
    isHit: true,
  },
  {
    id: 'prod-2',
    name: 'УШМ Makita 9558HNRG',
    slug: 'ushm-makita-9558hnrg',
    description: 'Угловая шлифовальная машина 125мм. Мощность 840Вт. Компактный корпус с тонкой рукояткой. Защита от случайного пуска.',
    price: 5490,
    oldPrice: null,
    categoryId: 'cat-1',
    image: '/products/ushm.png',
    rating: 4.6,
    reviewCount: 243,
    inStock: true,
    brand: 'Makita',
    isNew: false,
    isHit: true,
  },
  {
    id: 'prod-3',
    name: 'Дрель-шуруповёрт DeWalt DCD791D2',
    slug: 'dewalt-dcd791d2',
    description: 'Аккумуляторная дрель-шуруповёрт 18В с бесщёточным двигателем. 2 скорости, 15 позиций крутящего момента. Комплект 2 АКБ.',
    price: 16990,
    oldPrice: 19990,
    categoryId: 'cat-1',
    image: '/products/drel.png',
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    brand: 'DeWalt',
    isNew: true,
    isHit: false,
  },
  {
    id: 'prod-4',
    name: 'Циркулярная пила Makita HS7601',
    slug: 'makita-hs7601',
    description: 'Циркулярная пила 190мм. Мощность 1200Вт. Глубина пропила 66мм. Легкий компактный корпус для удобной работы.',
    price: 12990,
    oldPrice: null,
    categoryId: 'cat-1',
    image: '/products/cirk-pila.png',
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    brand: 'Makita',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-5',
    name: 'Электролобзик Bosch GST 150 CE',
    slug: 'bosch-gst-150-ce',
    description: 'Профессиональный лобзик с регулировкой оборотов. Мощность 780Вт. Подошва с противоскользящим покрытием. Система SDS для быстрой замены пилки.',
    price: 11490,
    oldPrice: 13490,
    categoryId: 'cat-1',
    image: '/products/lobzik.png',
    rating: 4.7,
    reviewCount: 34,
    inStock: true,
    brand: 'Bosch',
    isNew: false,
    isHit: false,
  },

  // Ручной инструмент
  {
    id: 'prod-6',
    name: 'Набор ключей комбинированных 14 пр.',
    slug: 'nabor-klyuchey-14',
    description: 'Профессиональный набор комбинированных ключей 6-24мм. Хром-ванадиевая сталь. Удобный кейс для хранения.',
    price: 3490,
    oldPrice: 4290,
    categoryId: 'cat-2',
    image: '/products/keys.png',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    brand: 'Арсенал',
    isNew: false,
    isHit: true,
  },
  {
    id: 'prod-7',
    name: 'Набор отвёрток 12 пр.',
    slug: 'nabor-otvertok-12',
    description: 'Набор из 12 отвёрток: плоские, крестовые, звёздочки. Магнитные наконечники. Прорезиненные рукоятки.',
    price: 1290,
    oldPrice: null,
    categoryId: 'cat-2',
    image: '/products/otvertki.png',
    rating: 4.4,
    reviewCount: 312,
    inStock: true,
    brand: 'Matrix',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-8',
    name: 'Молоток слесарный 500г',
    slug: 'molotok-slesarnyy-500',
    description: 'Слесарный молоток с фибергласовой рукояткой. Вес бойка 500г. Антивибрационная система.',
    price: 690,
    oldPrice: null,
    categoryId: 'cat-2',
    image: '/products/molotok.png',
    rating: 4.3,
    reviewCount: 87,
    inStock: true,
    brand: 'Stanley',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-9',
    name: 'Пассатижи комбинированные 200мм',
    slug: 'passatizhi-200',
    description: 'Комбинированные пассатижи с функцией кусачек. Хром-никелевая сталь. Двухкомпонентные рукоятки.',
    price: 590,
    oldPrice: null,
    categoryId: 'cat-2',
    image: '/products/passatizhi.png',
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    brand: 'Knipex',
    isNew: true,
    isHit: false,
  },
  {
    id: 'prod-10',
    name: 'Рулетка измерительная 5м',
    slug: 'ruletka-5m',
    description: 'Измерительная рулетка 5м, лента 25мм. Автоматический сматыватель. Фиксатор ленты. Ударопрочный корпус.',
    price: 390,
    oldPrice: 490,
    categoryId: 'cat-2',
    image: '/products/ruletka.png',
    rating: 4.6,
    reviewCount: 423,
    inStock: true,
    brand: 'Makita',
    isNew: false,
    isHit: true,
  },

  // Расходные материалы
  {
    id: 'prod-11',
    name: 'Диски алмазные для резки 125мм',
    slug: 'diski-almaznye-125',
    description: 'Алмазные отрезные диски 125мм для сухой и мокрой резки. Подходит для бетона, камня, керамики.',
    price: 890,
    oldPrice: null,
    categoryId: 'cat-3',
    image: '/products/diski-almaz.png',
    rating: 4.4,
    reviewCount: 78,
    inStock: true,
    brand: 'Distar',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-12',
    name: 'Сверла по бетону набор 5-12мм',
    slug: 'sverla-beton-5-12',
    description: 'Набор сверл по бетону SDS-plus, 6 штук: 5, 6, 7, 8, 10, 12мм. Твёрдый сплав, победитовые наконечники.',
    price: 1490,
    oldPrice: 1890,
    categoryId: 'cat-3',
    image: '/products/sverla.png',
    rating: 4.3,
    reviewCount: 201,
    inStock: true,
    brand: 'Bosch',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-13',
    name: 'Наждачная бумага набор 50 листов',
    slug: 'nazhdachka-50',
    description: 'Набор наждачной бумаги 50 листов, зернистость P80-P400. Для шлифовки дерева, металла, пластика.',
    price: 490,
    oldPrice: null,
    categoryId: 'cat-3',
    image: '/products/nazhdachka.png',
    rating: 4.2,
    reviewCount: 134,
    inStock: true,
    brand: 'Sia',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-14',
    name: 'Диски отрезные по металлу 125мм 25шт',
    slug: 'diski-metall-125-25',
    description: 'Отрезные диски по металлу 125х1.2мм, 25 штук. Высокая производительность, минимальный расход.',
    price: 790,
    oldPrice: 990,
    categoryId: 'cat-3',
    image: '/products/diski-metal.png',
    rating: 4.6,
    reviewCount: 289,
    inStock: true,
    brand: 'Luga',
    isNew: true,
    isHit: true,
  },
  {
    id: 'prod-15',
    name: 'Биты для шуруповёрта набор 50 пр.',
    slug: 'bity-50',
    description: 'Набор из 50 бит и насадок: PH, PZ, Torx, Hex, Slotted. Магнитный держатель. Гальваническое покрытие.',
    price: 990,
    oldPrice: null,
    categoryId: 'cat-3',
    image: '/products/bity.png',
    rating: 4.5,
    reviewCount: 367,
    inStock: true,
    brand: 'Bosch',
    isNew: false,
    isHit: false,
  },

  // Садовая техника
  {
    id: 'prod-16',
    name: 'Бензопила Husqvarna 236',
    slug: 'husqvarna-236',
    description: 'Бензопила для бытового использования. 38.2 куб.см, 1.4кВт. Шина 35см. Система легкого старта.',
    price: 22990,
    oldPrice: 26490,
    categoryId: 'cat-4',
    image: '/products/benzopila.png',
    rating: 4.7,
    reviewCount: 94,
    inStock: true,
    brand: 'Husqvarna',
    isNew: false,
    isHit: true,
  },
  {
    id: 'prod-17',
    name: 'Триммер электрический Bosch AFS 23-37',
    slug: 'bosch-afs-23-37',
    description: 'Электрический триммер 950Вт. Ширина кошения 37см. Телескопическая штанга. Двойная леска.',
    price: 7990,
    oldPrice: null,
    categoryId: 'cat-4',
    image: '/products/trimmer.png',
    rating: 4.3,
    reviewCount: 56,
    inStock: true,
    brand: 'Bosch',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-18',
    name: 'Газонокосилка Makita PLM4621',
    slug: 'makita-plm4621',
    description: 'Бензиновая газонокосилка. Двигатель 140сс. Ширина скашивания 46см. Травосборник 60л. 5 уровней высоты.',
    price: 34990,
    oldPrice: null,
    categoryId: 'cat-4',
    image: '/products/kosilka.png',
    rating: 4.8,
    reviewCount: 42,
    inStock: true,
    brand: 'Makita',
    isNew: true,
    isHit: false,
  },
  {
    id: 'prod-19',
    name: 'Кусторез аккумуляторный DeWalt',
    slug: 'dewalt-kustorez',
    description: 'Аккумуляторный кусторез 18В. Длина лезвия 55см. Время работы до 45мин. (АКБ в комплект не входит)',
    price: 11990,
    oldPrice: 13990,
    categoryId: 'cat-4',
    image: '/products/kustorez.png',
    rating: 4.4,
    reviewCount: 28,
    inStock: false,
    brand: 'DeWalt',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-20',
    name: 'Воздуходовка Stihl BGE 71',
    slug: 'stihl-bge-71',
    description: 'Электрическая воздуходовка. Мощность 1100Вт. Скорость воздушного потока 71м/с. Функция всасывания.',
    price: 8490,
    oldPrice: null,
    categoryId: 'cat-4',
    image: '/products/vozduhovka.png',
    rating: 4.5,
    reviewCount: 37,
    inStock: true,
    brand: 'Stihl',
    isNew: false,
    isHit: false,
  },

  // Строительное оборудование
  {
    id: 'prod-21',
    name: 'Бетономешалка 130л',
    slug: 'betonomeshalka-130',
    description: 'Бетоносмеситель 130л. Мощность 800Вт. Чугунный венец. Наклонный барабан. Колёса для транспортировки.',
    price: 24990,
    oldPrice: 28990,
    categoryId: 'cat-5',
    image: '/products/betonomeshalka.png',
    rating: 4.6,
    reviewCount: 63,
    inStock: true,
    brand: 'Лебедянь',
    isNew: false,
    isHit: true,
  },
  {
    id: 'prod-22',
    name: 'Строительные леса 3м',
    slug: 'lesa-3m',
    description: 'Передвижные строительные леса. Высота 3м. Площадка 1.5х0.7м. Грузоподъёмность 200кг. Колёса с тормозом.',
    price: 14990,
    oldPrice: null,
    categoryId: 'cat-5',
    image: '/products/lesa.png',
    rating: 4.4,
    reviewCount: 19,
    inStock: true,
    brand: 'Sokol',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-23',
    name: 'Компрессор воздушный 50л',
    slug: 'kompressor-50',
    description: 'Поршневой компрессор 50л. 2.2кВт, 8 бар. 2700 об/мин. Прямой привод. 2 манометра.',
    price: 17990,
    oldPrice: 20990,
    categoryId: 'cat-5',
    image: '/products/kompressor.png',
    rating: 4.7,
    reviewCount: 78,
    inStock: true,
    brand: 'Fubag',
    isNew: false,
    isHit: false,
  },
  {
    id: 'prod-24',
    name: 'Генератор бензиновый 3кВт',
    slug: 'generator-3kw',
    description: 'Бензиновый генератор 3кВт. 4-тактный двигатель. Автоматическая регулировка напряжения. 2 розетки 220В.',
    price: 29990,
    oldPrice: null,
    categoryId: 'cat-5',
    image: '/products/generator.png',
    rating: 4.5,
    reviewCount: 45,
    inStock: true,
    brand: 'Hyundai',
    isNew: true,
    isHit: true,
  },
  {
    id: 'prod-25',
    name: 'Виброплита 60кг',
    slug: 'vibroplita-60',
    description: 'Бензиновая виброплита. Вес 60кг. Центробежная сила 10кН. Глубина уплотнения 30см. Водяной бак.',
    price: 39990,
    oldPrice: 45990,
    categoryId: 'cat-5',
    image: '/products/vibroplita.png',
    rating: 4.8,
    reviewCount: 23,
    inStock: false,
    brand: 'Wacker Neuson',
    isNew: false,
    isHit: false,
  },
];

async function main() {
  console.log('🌱 Начинаем заполнение базы данных...');

  // Очистка существующих данных
  await db.cartItem.deleteMany();
  await db.product.deleteMany();
  await db.category.deleteMany();

  // Создание категорий
  for (const category of categories) {
    await db.category.create({ data: category });
  }
  console.log(`✅ Создано ${categories.length} категорий`);

  // Создание товаров
  for (const product of products) {
    await db.product.create({ data: product });
  }
  console.log(`✅ Создано ${products.length} товаров`);

  console.log('🎉 Заполнение базы данных завершено!');
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
